version: '3'
services: 
  db: 
    container_name: 'mysql'
    ports:
      - 3306:3306
    restart: always
    image: mysql:5.7
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: asdhhwaoihsos
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --init_connect='SET NAMES utf8mb4'
      --lower_case_table_names=1
      --max_connections=400
      --max_connect_errors=1000
      --explicit_defaults_for_timestamp=true
      --max_allowed_packet=128M
      --interactive_timeout=1800
      --wait_timeout=1800
      --tmp_table_size=134217728
      --max_heap_table_size=134217728
      --sort_buffer_size=2097152
      --back_log=600
      --external-locking=FALSE
      --thread_cache_size=300
      --query_cache_limit=4M
      --read_rnd_buffer_size=16M
      --bulk_insert_buffer_size=64M
      --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    volumes: 
      - ./data:/var/lib/mysql
